---

- name: Set samba_create_home_dirs flag on and keep it persistent across reboots
  seboolean:
    name: samba_create_home_dirs
    state: no
    persistent: yes
  tags: samba
  
- name: Set samba_export_all_rw flag on and keep it persistent across reboots
  seboolean:
    name: samba_export_all_rw
    state: no
    persistent: yes
  tags: samba
  
- name: Set use_samba_home_dirs  flag on and keep it persistent across reboots
  seboolean:
    name: use_samba_home_dirs 
    state: no
    persistent: yes
  tags: samba

- name: delete share directory
  file:
    path: "{{ directory_path }}"
    state: absent
  tags: samba

